### ISSUE TITLE
Bug while placing a card

### ISSUE THREAD

**Issue by misiowski0717** [Calemi/PlayingCards#1]
When placing a card on any surface with rmb, the card dissapears and a texture seen in the photo appears on screen. Texture dissapears after breaking the deck.
Mod version 1.0.2, forge 31.2.45
Bug is not present in 1.0.0 version
![Bug](https://user-images.githubusercontent.com/74064751/98388879-976fe800-2053-11eb-87ac-88ad1fcbbfb2.jpg)

**Comment by Calemi** [comment]
Thanks! I have no idea how I missed this, update should be out soon!
